### build_ddsFull.R ###############################################################################
# This script takes a set of count tables generated by previous steps and build a DESeqDataSet
# object that will be used by downstream scripts.

### PREAMBLE ######################################################################################
# Settings for environment

# Define working directory
setwd("~/angiogenesis_transcriptome/scripts/");

# Add some locally installed libraries to path
# .libPaths("~/R/lib/");

# Load required libraries and datasets
library( DESeq2 );

### FUNCTIONS #####################################################################################

# Load function mergeDataframesByRownames
source("mergeDataframesByRownames.R");

### DATA ANALYSIS #################################################################################

# Initialize object 'tmp' to hold all temporary objects
tmp <- list();

# Initialize empty count data frame to be populated
tmp$counts.df <- data.frame();

# Load counts into data frame
for ( file in list.files(path="aux_files/counts_by_gene", pattern="*.count.txt$", full.names = TRUE) ) {

  tmp$sample.count <- read.table(
    file = file,
    sep = "\t",
    header = FALSE,
    row.names = 1
    );
  
  # Assing column name
  colnames(tmp$sample.count) <- gsub(".count.txt$", "", basename(file) );
  
  # Merge two data frames by rownames  
  tmp$counts.df <- mergeDataframesByRownames(tmp$counts.df, tmp$sample.count);
  };

# Remove variable that will not be used anymore
rm( file );

# Remove HTSeq special counters rows
tmp$counts.df <- tmp$counts.df[! grepl("^__", rownames(tmp$counts.df) ), ];

# Sum counts based in the column names
tmp$allColSamples <- gsub( "-\\d+$", "", colnames(tmp$counts.df) );
tmp$sp <- split( seq( along = tmp$allColSamples ), tmp$allColSamples );
tmp$countdata <- sapply(tmp$sp, function(columns) rowSums( tmp$counts.df[, columns, drop=FALSE] ) );

# Get statistics from HTSeq special counters rows. Need to skip lines removal (few steps earlier)
# round( t( t( tmp$countdata[ grepl("^__", rownames(tmp$countdata) ), ]  ) / colSums(tmp$countdata) ), 3);
  
# Change '_' for '.' on sample R12.5
colnames(tmp$countdata) <- gsub(
  pattern = "R12_5", 
  replacement = "R12.5", 
  x = colnames(tmp$countdata)
  );

# Create a factor defining each experimental group (P = Control or R = Retinopathy/Experimetnal)
tmp$Treat.factor <- factor(
  gsub(
    pattern = "^(R|P)(.*)_(1|2)$",
    replacement = "\\1", 
    x = colnames(tmp$countdata)
    )
  );

# Create a factor defining each experimental time (12, 12.5, 15 or 17)  
tmp$Time.factor <- factor(
  gsub(
    pattern = "^(R|P)(.*)_(1|2)$",
    replacement = "\\2",
    x = colnames(tmp$countdata)
    )
  );

# Create a factor defining experimental batches (1 or 2)  
tmp$Batch.factor <- factor(
  gsub(
    pattern = "^(R|P)(.*)_(1|2)$",
    replacement = "\\3",
    x = colnames(tmp$countdata)
    )
  );

# Create data frame coldata with metadata
tmp$coldata <- data.frame(
  Treat = tmp$Treat.factor,
  Time = tmp$Time.factor,
  Batch = tmp$Batch.factor,
  row.names = colnames(tmp$countdata)
  );

# Build ddsFull object
ddsFull <- DESeqDataSetFromMatrix(
  countData = tmp$countdata,
  colData = tmp$coldata,
  design = ~ Batch + Time + Treat
  );

# Remove all temporary objects
rm( tmp );
